"""
PALACE AI

Chat Response
"""

from __future__ import annotations

from dataclasses import dataclass

from core.chunk import Chunk


@dataclass(slots=True)
class ChatResponse:
    """
    Response generated by PALACE AI.
    """

    answer: str

    sources: list[Chunk]
