"""
PALACE AI - Domain Model

This module defines the business language of PALACE AI.

The domain must never depend on technologies such as:
- OpenAI
- LangChain
- Streamlit
- FAISS
- Chroma
- Oracle

Only business concepts belong here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


# ============================================================
# VALUE OBJECTS
# ============================================================

class Area(Enum):
    """
    Business area that owns the knowledge.
    """

    HUMAN_RESOURCES = "human_resources"
    ACCOUNTING = "accounting"


class DocumentType(Enum):
    """
    Supported document types.
    """

    PDF = "pdf"
    CSV = "csv"


# ============================================================
# ENTITIES
# ============================================================

@dataclass(frozen=True)
class Document:
    """
    Represents a business document.

    A document is the source of knowledge.
    """

    id: str
    name: str
    area: Area
    document_type: DocumentType


@dataclass(frozen=True)
class Knowledge:
    """
    Represents organizational knowledge extracted from a document.
    """

    id: str
    document: Document


@dataclass(frozen=True)
class Question:
    """
    Represents a user question.
    """

    text: str
    area: Area | None = None


@dataclass(frozen=True)
class Answer:
    """
    Represents the answer generated by PALACE AI.
    """

    text: str
    sources: list[str] = field(default_factory=list)


# ============================================================
# DOMAIN SERVICES
# ============================================================

class KnowledgeBase:
    """
    Represents the company's knowledge base.

    This class is a domain service.

    Infrastructure implementations such as
    FAISS, Chroma or PostgreSQL will be
    connected later.
    """

    pass